name: Generate Installable Plugin or Theme, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Create artifact
        run : |
          git archive -o minimalistflex-${{ github.ref_name }}.zip --prefix minimalistflex/ HEAD 
          ls
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: minimalistflex-${{ github.ref_name }}
            path: minimalistflex-${{ github.ref_name }}.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: minimalistflex-${{ github.ref_name }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
